version: '3'
services:
  skaf:
    container_name: skaf
    image: skaf:dev
    build:
      context: ..
      dockerfile: skaf/Dockerfile
    ports:
      - "1332:6543"
    volumes:
      - .:/home/skaf/skaf
      - ../coder-core:/home/skaf/coder-core
      - /home/skaf/skaf/skaf.egg-info
      - /home/skaf/coder-core/codercore.egg-info
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: >
      bash -c "alembic -c skaf/local-develop.ini upgrade heads &&
      pserve --reload skaf/develop.ini"
  db:
    container_name: skaf-db
    image: postgres:11
    ports:
      - "1333:5432"
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=skaf
